### ISSUE TITLE
Sous menu des paramètres supplémentaires : "One-handed"

### ISSUE THREAD

**Issue by s0me-1** [cpasmoi/miui-xml-V6-FRENCH#17]
Soit dans Paramètres > Paramètres additionnels > One-Handed

Il n'y a rien de traduis et je n'arrive pas a mettre la main sur le XML pour le faire ^^. Vous savez ou il se trouve ?

EDIT:
Je viens de voir ça:
https://github.com/cpasmoi/miui-xml-V6-FRENCH/issues/4

ce que je comprends pas c'est que les XML sont classé par appareil, on doit utiliser lesquels nous ?

**Comment by cpasmoi** [comment]
cancro

**Comment by cpasmoi** [comment]
je vois que c'est deja traduit dans la dernier version, il manque juste la traduction pour "4 inches /3.5 inches"
