### ISSUE TITLE
Erreur de Traduction dans la sauvegarde des mots de passe du Navigateur MIUI

### ISSUE THREAD

**Issue by Gaubry31** [cpasmoi/miui-xml-V6-FRENCH#25]
![trad fr](https://cloud.githubusercontent.com/assets/10923252/6106824/4dc93242-b065-11e4-8bd1-69fe0e5ef92a.png)
Voici une erreur de traduction dans le navigateur MIUI 5.2.6 MI4

**Comment by cpasmoi** [comment]
merci
