### ISSUE TITLE
Erreur de place sur choix des fonds d'écran

### ISSUE THREAD

**Issue by Gaubry31** [cpasmoi/miui-xml-V6-FRENCH#28]
Deux petit bug de traduction et mise en place.
Pour les fonds d'écran, le choix du menu  de vérrouillage et masqué.

Pour le navigateur, c'est lors de l'enregistrement d'un mot de passe. le choix du milieu devrait etre "enregistrer"

Thx,
![fond ecran](https://cloud.githubusercontent.com/assets/10923252/6148103/ac9fed5c-b1fe-11e4-9dda-5851e3fed17b.jpg)

![internet](https://cloud.githubusercontent.com/assets/10923252/6148102/ac9f471c-b1fe-11e4-9dcf-b5fdc04e5cf3.jpg)

**Comment by cpasmoi** [comment]
salut, oui c'est deja corrigé pour le browser, pour l'autre je vais jeter un peil, tu doit avoir un ecran non 1080p ? sur mon tel c'est affiché en entier, je vais voir pour ce que je peux faire, peut etre raccourcir ce texte sur les petites resolutions. n'hesite pas si tu voit d'autres textes coupés sur ton tel, c'est lequel d'ailleur ?

**Comment by cpasmoi** [comment]
J'ai aussi deja remplacer "non" par "annuler", sur le premier screen.

**Comment by Gaubry31** [comment]
un Mi4 en miui v6 5.2.6 pourtant bien en 1080p

**Comment by cpasmoi** [comment]
ha oui j'avais tester sur la mipad en fait, je vais essayer de corriger ca

**Comment by Gaubry31** [comment]
en tout cas merci pour tous le travail que tu fournis pour mettre en FR la rom MIUI :p
