### ISSUE TITLE
traduction bouton explorateur fichier miui

### ISSUE THREAD

**Issue by Gaubry31** [cpasmoi/miui-xml-V6-FRENCH#30]
Un bouton n'a pas etait traduit lors d'une sélection dans l'explorateur miui
Mi4 
![screenshot_2015-03-10-22-33-56](https://cloud.githubusercontent.com/assets/10923252/6585891/96e98612-c775-11e4-8bf3-b1b331b049d0.png)
v6 5.3.6

**Comment by cpasmoi** [comment]
oui, c'est bon c'etait un oubli de la part de xiaomi ;)
