### ISSUE TITLE
Une amélioration possible sur la traduction de l'application caméra

### ISSUE THREAD

**Issue by Darktitor** [cpasmoi/miui-xml-V6-FRENCH#35]
Bonjour,
Je ne sais pas comment m'y prendre pour faire des suggestions sur GitHub fin bon j'espère que vous comprendrez...
Je tiens à vous demandez si il est possible de changer le format de l'âge affiché par la camera:

Actuellement : Homme 26 années 
Correction : Homme 26 ans

Je pense que c'est plus correct ainsi ;)

(Changement de la ligne 106 (MIUICamera))

Merci encore pour le travail accompli :)
Cordialement, 
Alex

**Comment by cpasmoi** [comment]
salut je vais corriger, merci
